"""
ADOBMD unified data format writer
"""

import numpy as np
from typing import List, Dict, Tuple, Optional

class ADOBMDWriter:
    """Writer for ADOBMD unified data format"""
    
    def __init__(self):
        self.atoms: List[Dict] = []
        self.bonds: List[Tuple[int, int, int]] = []  # (i, j, type)
        self.atom_types: Dict[str, int] = {}  # element -> type_id
        self.type_masses: Dict[int, float] = {}  # type_id -> mass
        self.title = ""
        self.comment = ""
        self.box = [0.0, 0.0, 0.0]  # x, y, z box sizes
        self.qm_indices: List[int] = []  # 1-based atom indices for QM region
    
    def add_atom(self, element: str, x: float, y: float, z: float, 
                 molecule_id: int = 1, charge: float = 0.0, 
                 is_qm: bool = False, mass: Optional[float] = None):
        """Add an atom to the system"""
        
        # Assign atom type
        if element not in self.atom_types:
            type_id = len(self.atom_types) + 1
            self.atom_types[element] = type_id
            
            # Set mass (use provided or default)
            if mass is not None:
                self.type_masses[type_id] = mass
            else:
                # Will be filled later from database
                self.type_masses[type_id] = 0.0
        else:
            type_id = self.atom_types[element]
        
        atom = {
            'id': len(self.atoms) + 1,
            'type': type_id,
            'molecule': molecule_id,
            'element': element,
            'x': x,
            'y': y,
            'z': z,
            'charge': charge,
            'is_qm': is_qm
        }
        
        self.atoms.append(atom)
        
        if is_qm:
            self.qm_indices.append(len(self.atoms))
    
    def add_bond(self, atom1: int, atom2: int, bond_type: int = 1):
        """Add a bond between atoms"""
        self.bonds.append((atom1, atom2, bond_type))
    
    def set_box(self, x: float, y: float, z: float, padding: float = 5.0):
        """Set simulation box with optional padding"""
        if x > 0 and y > 0 and z > 0:
            self.box = [x + 2*padding, y + 2*padding, z + 2*padding]
        else:
            # Calculate from atomic coordinates
            coords = np.array([[a['x'], a['y'], a['z']] for a in self.atoms])
            min_coords = np.min(coords, axis=0)
            max_coords = np.max(coords, axis=0)
            size = max_coords - min_coords
            self.box = [size[0] + 2*padding, size[1] + 2*padding, size[2] + 2*padding]
    
    def write(self, filename: str):
        """Write ADOBMD unified data file"""
        
        with open(filename, 'w') as f:
            # Header
            f.write(f"# ADOBMD Unified Data File\n")
            if self.title:
                f.write(f"# Title: {self.title}\n")
            if self.comment:
                f.write(f"# Comment: {self.comment}\n")
            f.write(f"# Generated by ADOBMD Converter\n")
            f.write(f"\n")
            
            # Counts
            f.write(f"{len(self.atoms)} atoms\n")
            f.write(f"{len(self.bonds)} bonds\n")
            f.write(f"0 angles\n")
            f.write(f"0 dihedrals\n")
            f.write(f"0 impropers\n")
            f.write(f"\n")
            f.write(f"{len(self.atom_types)} atom types\n")
            if self.bonds:
                bond_types = len(set(b[2] for b in self.bonds))
                f.write(f"{bond_types} bond types\n")
            else:
                f.write(f"0 bond types\n")
            f.write(f"\n")
            
            # Box
            f.write(f"0.0 {self.box[0]:.6f} xlo xhi\n")
            f.write(f"0.0 {self.box[1]:.6f} ylo yhi\n")
            f.write(f"0.0 {self.box[2]:.6f} zlo zhi\n")
            f.write(f"\n")
            
            # Masses
            f.write(f"Masses\n\n")
            for type_id in sorted(self.atom_types.values()):
                element = [e for e, tid in self.atom_types.items() if tid == type_id][0]
                mass = self.type_masses[type_id]
                f.write(f"{type_id} {mass:.6f}  # {element}\n")
            f.write(f"\n")
            
            # Atoms
            f.write(f"Atoms\n\n")
            f.write(f"# id mol type q x y z [region]\n")
            
            for atom in self.atoms:
                region = "QM" if atom['is_qm'] else ""
                if region:
                    f.write(f"{atom['id']} {atom['molecule']} {atom['type']} "
                           f"{atom['charge']:.6f} {atom['x']:.6f} {atom['y']:.6f} "
                           f"{atom['z']:.6f} {region}\n")
                else:
                    f.write(f"{atom['id']} {atom['molecule']} {atom['type']} "
                           f"{atom['charge']:.6f} {atom['x']:.6f} {atom['y']:.6f} "
                           f"{atom['z']:.6f}\n")
            f.write(f"\n")
            
            # Bonds
            if self.bonds:
                f.write(f"Bonds\n\n")
                f.write(f"# id type atom1 atom2\n")
                for i, (a1, a2, btype) in enumerate(self.bonds, 1):
                    f.write(f"{i} {btype} {a1} {a2}\n")
                f.write(f"\n")
            
            # QM region summary
            if self.qm_indices:
                f.write(f"# QM Region Summary\n")
                f.write(f"# {len(self.qm_indices)} QM atoms\n")
                f.write(f"# QM indices: {', '.join(str(i) for i in self.qm_indices)}\n")
    
    def write_qm_region_file(self, filename: str):
        """Write separate QM region index file"""
        if self.qm_indices:
            with open(filename, 'w') as f:
                for idx in self.qm_indices:
                    f.write(f"{idx}\n")
    
    def get_statistics(self) -> Dict:
        """Get system statistics"""
        elements = {}
        for atom in self.atoms:
            elem = atom['element']
            elements[elem] = elements.get(elem, 0) + 1
        
        return {
            'atoms': len(self.atoms),
            'bonds': len(self.bonds),
            'atom_types': len(self.atom_types),
            'qm_atoms': len(self.qm_indices),
            'elements': elements,
            'box': self.box
        }